= Mediary
Jaime Silvela
v0.6, 2014-08-08
v0.5, 2014-07-11

Mediary is a tool to write and store events into a machine-readable format.

== Installation
go get github.com/jsilvela/mediary
go build github.com/jsilvela/mediary

== Usage
mediary <optional file>

Mediary goes into listening mode, reads from stdin line by line. +
You start a new entry by typing +
new { +
and finish with +
}

In the context of an entry, you can specify the following fields:

time: <my time>:: with the time either "today", or in the format "2014-01-30"

tags: <my tags>:: accepting a comma-separated list

text: <my text>:: the program goes into text mode, which allows multi-line text.

Outside of the context of an entry, each line is seen as a full and final sentence, 
containing some filters, and a reporting directive. +
Filters: week +
Reports: tags, latest +

For example, a line could be: week latest

To finish your session, +
exit

== Motivation
I've been keeping a notebook with health-related events, which has been pretty useful. I want to transition it to files, but plain text means that any reporting would be done with regex or similar. I'd like a good way to ask questions, and I think a SQL db is too heavy-weight. Hence this project.

== Details
Concept version coded in +go+ (this is my first program). Uses JSON for storage. +
Currently very much a CLI, but eventually would be nice to have this in iOS.
